Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64" # Используем Ubuntu 22.04 LTS
  config.vm.hostname = "webserver"

  # Проброс порта 8080 с гостевой машины на хостовую
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Автоматический запуск Ansible плейбука при поднятии стенда
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
